// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Information about a book (or article) in the library.
class BookInfo {
  /// Full path to the file (as a String for FFI).
  final String path;

  /// Display title (cleaned).
  final String title;

  /// Author (if known).
  final String author;

  /// File size in bytes.
  final BigInt sizeBytes;

  /// Type of book: "rsvp", "txt", or "epub".
  final String fileType;

  /// Category: "book" or "article".
  final String category;

  /// Progress percentage (0-100) if previously read, else None.
  final int? progressPercent;

  const BookInfo({
    required this.path,
    required this.title,
    required this.author,
    required this.sizeBytes,
    required this.fileType,
    required this.category,
    this.progressPercent,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      title.hashCode ^
      author.hashCode ^
      sizeBytes.hashCode ^
      fileType.hashCode ^
      category.hashCode ^
      progressPercent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookInfo &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          author == other.author &&
          sizeBytes == other.sizeBytes &&
          fileType == other.fileType &&
          category == other.category &&
          progressPercent == other.progressPercent;
}
