// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ProgressEntry {
  final BigInt wordIndex;
  final BigInt wordCount;
  final BigInt updatedAt;

  const ProgressEntry({
    required this.wordIndex,
    required this.wordCount,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      wordIndex.hashCode ^ wordCount.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressEntry &&
          runtimeType == other.runtimeType &&
          wordIndex == other.wordIndex &&
          wordCount == other.wordCount &&
          updatedAt == other.updatedAt;
}
