// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Configuration for word pacing delays and scaling factors.
class PacingConfig {
  final int longWordDelayMs;
  final int complexWordDelayMs;
  final int punctuationDelayMs;
  final int longWordScalePercent;
  final int complexWordScalePercent;
  final int punctuationScalePercent;

  const PacingConfig({
    required this.longWordDelayMs,
    required this.complexWordDelayMs,
    required this.punctuationDelayMs,
    required this.longWordScalePercent,
    required this.complexWordScalePercent,
    required this.punctuationScalePercent,
  });

  @override
  int get hashCode =>
      longWordDelayMs.hashCode ^
      complexWordDelayMs.hashCode ^
      punctuationDelayMs.hashCode ^
      longWordScalePercent.hashCode ^
      complexWordScalePercent.hashCode ^
      punctuationScalePercent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PacingConfig &&
          runtimeType == other.runtimeType &&
          longWordDelayMs == other.longWordDelayMs &&
          complexWordDelayMs == other.complexWordDelayMs &&
          punctuationDelayMs == other.punctuationDelayMs &&
          longWordScalePercent == other.longWordScalePercent &&
          complexWordScalePercent == other.complexWordScalePercent &&
          punctuationScalePercent == other.punctuationScalePercent;
}
