// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../storage/library_scanner.dart';
import '../storage/progress_store.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initLibrary({
  required String cacheFile,
  required String progressFile,
}) => RustLib.instance.api.crateApiLibraryInitLibrary(
  cacheFile: cacheFile,
  progressFile: progressFile,
);

Future<List<BookInfo>> getLibrary({required String rootDir}) =>
    RustLib.instance.api.crateApiLibraryGetLibrary(rootDir: rootDir);

Future<void> saveProgress({
  required String bookPath,
  required BigInt wordIndex,
  required BigInt wordCount,
}) => RustLib.instance.api.crateApiLibrarySaveProgress(
  bookPath: bookPath,
  wordIndex: wordIndex,
  wordCount: wordCount,
);

Future<ProgressEntry?> getProgress({required String bookPath}) =>
    RustLib.instance.api.crateApiLibraryGetProgress(bookPath: bookPath);

Future<void> deleteBook({required String bookPath}) =>
    RustLib.instance.api.crateApiLibraryDeleteBook(bookPath: bookPath);

Future<String> convertEpub({
  required String epubPath,
  required BigInt maxWords,
}) => RustLib.instance.api.crateApiLibraryConvertEpub(
  epubPath: epubPath,
  maxWords: maxWords,
);

Future<void> refreshCache({required String rootDir}) =>
    RustLib.instance.api.crateApiLibraryRefreshCache(rootDir: rootDir);
