// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'processor.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `read_epub_file`

Future<String> readFileContent({required String path}) =>
    RustLib.instance.api.crateApiProcessorReadFileContent(path: path);

Future<List<RsvpWord>> parseTextToRsvp({required String text}) =>
    RustLib.instance.api.crateApiProcessorParseTextToRsvp(text: text);

@freezed
sealed class RsvpWord with _$RsvpWord {
  const factory RsvpWord({
    required String left,
    required String center,
    required String right,
    required double delayFactor,
  }) = _RsvpWord;
}
