// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/pacing.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'reader.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `fallback_demo`

/// Creates a new reader.
/// If `book_path` is `None`, loads a built-in demo.
/// Supports `.rsvp` (parsed into memory) and `.ridx` (indexed store).
Future<ReaderHandle> createReader({String? bookPath}) =>
    RustLib.instance.api.crateApiReaderCreateReader(bookPath: bookPath);

/// Update the reader’s internal timer. Call frequently with current timestamp in ms.
/// Returns `true` if the current word changed.
Future<bool> readerUpdate({
  required ReaderHandle handle,
  required BigInt nowMs,
}) => RustLib.instance.api.crateApiReaderReaderUpdate(
  handle: handle,
  nowMs: nowMs,
);

/// Send a command to the reader.
Future<void> readerCommand({
  required ReaderHandle handle,
  required ReaderCommand cmd,
  required BigInt nowMs,
}) => RustLib.instance.api.crateApiReaderReaderCommand(
  handle: handle,
  cmd: cmd,
  nowMs: nowMs,
);

/// Get the current state of the reader.
Future<ReaderState> readerState({required ReaderHandle handle}) =>
    RustLib.instance.api.crateApiReaderReaderState(handle: handle);

/// Set the pacing configuration (delays and scales).
Future<void> setPacingConfig({
  required ReaderHandle handle,
  required PacingConfig config,
}) => RustLib.instance.api.crateApiReaderSetPacingConfig(
  handle: handle,
  config: config,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ReaderHandle>>
abstract class ReaderHandle implements RustOpaqueInterface {}

@freezed
sealed class ReaderCommand with _$ReaderCommand {
  const ReaderCommand._();

  const factory ReaderCommand.play() = ReaderCommand_Play;
  const factory ReaderCommand.pause() = ReaderCommand_Pause;
  const factory ReaderCommand.seekTo(BigInt field0) = ReaderCommand_SeekTo;
  const factory ReaderCommand.scrub(int field0) = ReaderCommand_Scrub;
  const factory ReaderCommand.rewindSentence() = ReaderCommand_RewindSentence;
  const factory ReaderCommand.adjustWpm(int field0) = ReaderCommand_AdjustWpm;
  const factory ReaderCommand.setWpm(int field0) = ReaderCommand_SetWpm;
}

@freezed
sealed class ReaderState with _$ReaderState {
  const factory ReaderState({
    required String currentWord,
    required BigInt currentIndex,
    required BigInt totalWords,
    required int wpm,
    required bool isPlaying,
    required bool atEnd,
    required int progressPercent,
  }) = _ReaderState;
}
